server {
    listen 80;
    root /usr/share/nginx/html;
    index index.html;

    location ~* \.(html)$ {
        add_header Cache-Control "no-cache, must-revalidate";
    }

    location ~* \.(css|js)$ {
        add_header Cache-Control "no-cache, must-revalidate";
    }
}